--CREATE TYPE "level" AS ENUM ('private', 'collaboration', 'shared','public');

CREATE TABLE "share_level"(
 "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
"shared_level" level NOT NULL,
  "active" BOOLEAN   
);