

CREATE TABLE "topic"(
  -- might need to set on delete cascade
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "topic_title" TEXT NOT NULL,
  "topic_content" TEXT NOT NULL,
  "topic_owner" INTEGER REFERENCES "user"(id) ON DELETE CASCADE NOT NULL ,
  "level" INTEGER REFERENCES "share_level"(id)  DEFAULT 1  NOT NULL
 

  
  );

   -- "topic_owner" INTEGER NOT NULL