


CREATE TABLE "thought" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "thought_title" TEXT NOT NULL UNIQUE,
  "thought_content" TEXT NOT NULL,
  "thought_topic" INTEGER REFERENCES topic(id)
-- "thought_type" TEXT //ENUM
  );

  