


CREATE TABLE "thought"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "thought_title" TEXT NOT NULL UNIQUE,
  "thought_content" TEXT NOT NULL,
  "thought_owner" INTEGER REFERENCES "user"(id),
  "thought_topic" INTEGER 
-- "thought_type" TEXT //ENUM
  );

  