CREATE TABLE "thought"(
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 "thought_title" TEXT NOT NULL,
  "thought_content" TEXT NOT NULL,
  "thought_owner" INTEGER REFERENCES "user"(id) ON DELETE CASCADE,
  "thought_topic" INTEGER REFERENCES "topic"(id) ON DELETE CASCADE,
  "level" INTEGER REFERENCES "share_level"(id) DEFAULT 1  NOT NULL,
  "date_modified" TIMESTAMP DEFAULT now() NOT NULL
-- "thought_type" TEXT //ENUM
  ); 