CREATE TABLE "comments"(
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "thought_id" INTEGER REFERENCES "thought"(id) ON DELETE CASCADE NOT NULL,
    "commenter_id" INTEGER REFERENCES "fokul_users"(id) ON DELETE CASCADE NOT NULL,
    "comment_content" TEXT NOT NULL,
    
    "date_posted" TIMESTAMP DEFAULT now() NOT NULL
)